Repository 100-hours-a-week/8-pumati-fe, pull requests merged in 2025-06, with the labels that each got.

#136 외부인 회원정보 수정 동작안하는 문제 해결
  src/features/user/components/user-profile-edit-form/UserProfileEditForm.tsx
Labels: 🐞 Bug-Critical

#141 Jenkinsfile, Dockerfile, .dockerignore 추가
  .dockerignore
  Jenkinsfile
  dockerfile
Labels: 🌏 Deploy

#142 뱃지 관련 기능 구현
  src/app/(auth-header)/signup/page.tsx
  src/app/(header)/mypage/page.tsx
  src/components/modal/AlertModal.tsx
  src/constants/badge-tag.ts
  src/constants/error-message.ts
  src/constants/index.ts
  src/constants/query-key.ts
  src/features/auth/components/login-callback-content/LoginCallbackContent.tsx
  src/features/auth/hooks/useRefresh.tsx
  src/features/auth/hooks/useTeamList.tsx
  src/features/badge/components/badge-fetcher/BadgeFetcher.tsx
  src/features/badge/components/badge-fetcher/index.ts
  src/features/badge/components/badge-item/BadgeItem.tsx
  src/features/badge/components/badge-item/index.ts
  src/features/badge/components/badge-list/BadgeList.tsx
  src/features/badge/components/badge-list/index.ts
  src/features/badge/components/badge-modal-content/BadgeModalContent.tsx
  src/features/badge/components/badge-modal-content/index.ts
  src/features/badge/components/badge/Badge.tsx
  src/features/badge/components/badge/index.ts
  src/features/badge/components/badges-container/BadgesContainer.tsx
  src/features/badge/components/badges-container/index.ts
  src/features/badge/components/edit-badge-modal-content/EditBadgeModalContent.tsx
  src/features/badge/components/edit-badge-modal-content/index.ts
  src/features/badge/components/edit-badge/EditBadge.tsx
  src/features/badge/components/edit-badge/index.ts
  src/features/badge/components/index.ts
  src/features/badge/components/tag/TagItem.tsx
  src/features/badge/components/tag/TagList.tsx
  src/features/badge/components/tag/index.ts
  src/features/badge/hooks/index.ts
  src/features/badge/hooks/useEditBadge.tsx
  src/features/badge/hooks/useMyBadges.tsx
  src/features/badge/hooks/useReceiveBadge.tsx
  src/features/badge/schemas/badge.ts
  src/features/badge/schemas/index.ts
  src/features/badge/services/index.ts
  src/features/comment/hooks/useComments.tsx
  src/features/comment/hooks/useCreateComment.tsx
  src/features/comment/hooks/useDeleteComment.tsx
  src/features/comment/hooks/useEditComment.tsx
  src/features/project/components/edit-form/EditForm.tsx
  src/features/project/components/project-detail-container/Dashboard.tsx
  src/features/project/components/project-detail-container/Description.tsx
  src/features/project/components/project-detail-container/ProjectDetailContainer.tsx
  src/features/project/components/project-detail-fetcher/ProjectDetailFetcher.tsx
  src/features/project/components/projects-fetcher/ProjectsFetcher.tsx
  src/features/project/components/tag/TagItem.tsx
  src/features/project/hooks/useCheckProjectExists.tsx
  src/features/project/hooks/useCreateProject.tsx
  src/features/project/hooks/useProjects.tsx
  src/features/project/schemas/project.ts
  src/features/user/components/dashboard/Dashboard.tsx
  src/features/user/components/dashboard/DashboardItem.tsx
  src/features/user/components/information/Information.tsx
  src/features/user/hooks/useAttendanceState.tsx
  src/features/user/hooks/useCheckAttendance.tsx
  src/features/user/hooks/useDashboard.tsx
  src/utils/count.ts
Labels: 🚀 Feature, 🎨 Style

#144 본인 프로젝트 품앗이 막기
  src/features/project/components/project-detail-container/Description.tsx
Labels: 🐞 Bug

#145 dev CI 코드 추가
  .dockerignore
  Jenkinsfile
  ci/dev/.dockerignore
  ci/dev/Dockerfile.dev
  ci/dev/Jenkinsfile
  ci/dev/README.md
  dockerfile
Labels: 🌏 Deploy

#150 챗봇 기능 구현
  package.json
  pnpm-lock.yaml
  src/app/(header)/layout.tsx
  src/assets/images/mati-chatbot.png
  src/components/dropdown/Dropdown.tsx
  src/components/icons/ArrowIcon.tsx
  src/components/icons/NavArrowIcon.tsx
  src/components/icons/PauseIcon.tsx
  src/components/icons/index.ts
  src/components/modal/AlertModal.tsx
  src/components/modal/ConfirmModal.tsx
  src/constants/chatbot-question.ts
  src/constants/index.ts
  src/constants/query-key.ts
  src/features/auth/components/auth-header/AuthHeader.tsx
  src/features/chatbot/components/chat-form/ChatForm.tsx
  src/features/chatbot/components/chat-form/index.ts
  src/features/chatbot/components/chat-input/ChatInput.tsx
  src/features/chatbot/components/chat-input/index.ts
  src/features/chatbot/components/chatbot-button/ChatbotButton.tsx
  src/features/chatbot/components/chatbot-button/index.ts
  src/features/chatbot/components/chatbot-panel/ChatbotPanel.tsx
  src/features/chatbot/components/chatbot-panel/index.ts
  src/features/chatbot/components/chatting-item/ChattingItem.tsx
  src/features/chatbot/components/chatting-item/index.ts
  src/features/chatbot/components/default-questions/DefaultQuestions.tsx
  src/features/chatbot/components/default-questions/index.ts
  src/features/chatbot/components/index.ts
  src/features/chatbot/hooks/index.ts
  src/features/chatbot/hooks/useCreateChatbotSessionId.tsx
  src/features/chatbot/hooks/useDisconnectChatbot.tsx
  src/features/chatbot/hooks/useSSE.tsx
  src/features/chatbot/hooks/useSendChatbotQuestion.tsx
  src/features/chatbot/schemas/chatting.ts
  src/features/chatbot/schemas/index.ts
  src/features/chatbot/schemas/question.ts
  src/features/chatbot/services/index.ts
  src/features/project/components/carousel/SwipeButton.tsx
  src/features/project/components/project-detail-container/ProjectDetailContainer.tsx
  src/features/user/components/information/Information.tsx
  src/hooks/index.ts
  src/hooks/useLockOutsideScroll.tsx
Labels: 🚀 Feature, 🎨 Style

#155 품앗이 툴팁
  src/components/icons/InfoIcon.tsx
  src/components/icons/index.ts
  src/features/project/components/project-detail-container/Dashboard.tsx
  src/features/project/components/project-detail-container/Tooltip.tsx
  src/features/project/components/simple-projects/SimpleProjects.tsx
Labels: 🚀 Feature, 🎨 Style

#156 API 요청 함수 커스텀(fetch)
  src/app/(header)/projects/page.tsx
  src/features/auth/hooks/useAuth.tsx
  src/features/auth/hooks/useRefresh.tsx
  src/features/auth/hooks/useSignup.tsx
  src/features/auth/hooks/useTeamList.tsx
  src/features/auth/schemas/signup.ts
  src/features/auth/services/index.ts
  src/features/badge/components/badge-fetcher/BadgeFetcher.tsx
  src/features/badge/hooks/useMyBadges.tsx
  src/features/badge/schemas/badge.ts
  src/features/badge/services/index.ts
  src/features/chatbot/components/chatbot-panel/ChatbotPanel.tsx
  src/features/chatbot/services/index.ts
  src/features/comment/hooks/useComments.tsx
  src/features/comment/services/index.ts
  src/features/project/components/project-detail-container/MemberList.tsx
  src/features/project/components/ranked-projects/RankedProjects.tsx
  src/features/project/hooks/useCreateProject.tsx
  src/features/project/hooks/useProjects.tsx
  src/features/project/schemas/new-project.ts
  src/features/project/schemas/project.ts
  src/features/project/services/index.ts
  src/features/user/components/attendance/Attendance.tsx
  src/features/user/components/dashboard/DashboardFetcher.tsx
  src/features/user/hooks/useCheckAttendance.tsx
  src/features/user/schemas/attendance.ts
  src/features/user/services/index.ts
  src/schemas/api-client.ts
  src/schemas/index.ts
  src/utils/api-client.ts
  src/utils/date.ts
  src/utils/error.ts
Labels: 🔨 Refactor

#157 뱃지 확대 모달 구현
  src/app/(header)/mypage/page.tsx
  src/components/modal/AlertModal.tsx
  src/features/badge/components/badge-fetcher/BadgeFetcher.tsx
  src/features/badge/components/badge-fetcher/index.ts
  src/features/badge/components/badge-item/BadgeItem.tsx
  src/features/badge/components/badge/Badge.tsx
  src/features/badge/components/badges-container/BadgesContainer.tsx
  src/features/badge/components/index.ts
  src/features/project/components/project-detail-container/Description.tsx
Labels: 🚀 Feature, 🎨 Style

#158 뱃지 수정 요청 바디 스키마 수정
  src/features/badge/components/edit-badge-modal-content/EditBadgeModalContent.tsx
  src/features/badge/schemas/badge.ts
Labels: 🐞 Bug-Critical

#165 토큰 재발급 기능 구현
  src/components/header/Header.tsx
  src/components/header/NavBar.tsx
  src/components/header/NavMenuItem.tsx
  src/features/auth/components/auth-provider/AuthProvider.tsx
  src/features/auth/components/login-callback-content/LoginCallbackContent.tsx
  src/features/auth/components/signup/container/SignupContainer.tsx
  src/features/auth/components/signup/form/SecondStep.tsx
  src/features/auth/hooks/useAuth.tsx
  src/features/auth/hooks/useCodeVerification.tsx
  src/features/auth/hooks/useLogout.tsx
  src/features/auth/hooks/useSignup.tsx
  src/features/badge/components/badges-container/BadgesContainer.tsx
  src/features/badge/components/edit-badge-modal-content/EditBadgeModalContent.tsx
  src/features/badge/hooks/useMyBadges.tsx
  src/features/chatbot/components/chatbot-panel/ChatbotPanel.tsx
  src/features/chatbot/hooks/useSSE.tsx
  src/features/comment/components/comment-item/CommentItem.tsx
  src/features/comment/components/comment-item/CommentMenu.tsx
  src/features/comment/components/create-comment-modal-wrapper/CreateCommentModalWrapper.tsx
  src/features/comment/components/edit-comment-modal-wrapper/EditCommentModalWrapper.tsx
  src/features/project/components/create-form/CreateForm.tsx
  src/features/project/components/edit-form/EditForm.tsx
  src/features/project/components/project-detail-container/Description.tsx
  src/features/project/hooks/useCheckProjectExists.tsx
  src/features/project/hooks/useCreateProject.tsx
  src/features/project/hooks/useDeleteProject.tsx
  src/features/project/hooks/useEditProject.tsx
  src/features/user/components/attendance/Attendance.tsx
  src/features/user/components/dashboard/DashboardFetcher.tsx
  src/features/user/components/information/Information.tsx
  src/features/user/components/user-profile-edit-form/UserProfileEditForm.tsx
  src/features/user/components/withdraw-modal-content/WithdrawModalContent.tsx
  src/features/user/hooks/useAttendanceState.tsx
  src/features/user/hooks/useEditUserProfile.tsx
  src/features/user/hooks/useWithdraw.tsx
  src/providers.tsx
  src/store/index.ts
  src/utils/api-client.ts
Labels: 🚀 Feature

#167 V2 배포에 따른 Jenkinsfile 업데이트
  Jenkinsfile
Labels: 🌏 Deploy

#169 Jenkinsfile 수정
  Jenkinsfile
Labels: 🌏 Deploy

#171 Protected route middleware로 리팩토링
  src/app/(auth-header)/layout.tsx
  src/app/(header)/mypage/layout.tsx
  src/middleware.ts
Labels: 🔨 Refactor

#174 폰트 최적화
  src/assets/fonts/index.ts
  src/assets/fonts/pretendard/PretendardSubset.woff2
  src/assets/fonts/pretendard/PretendardVariable.woff2
Labels: 🔨 Refactor
